"""Import existing MP3 files (with optional Narracast sidecars) into a project.

Typical use case: a user has a folder of MP3s generated outside Narracast, or
generated by an earlier Narracast run that was not linked to any project.

Behaviour
---------
* The folder is scanned for ``*.mp3`` files (non-recursive, sorted naturally).
* For each MP3, the matching sidecar ``<stem>.json`` is read if present.
* Chapters are created as follows:

  - Sidecar present and audio file valid → status ``generated``,
    ``output_path`` points to the MP3, ``text`` from ``source_text``.
  - No sidecar (or sidecar unreadable) → status ``draft``, ``output_path``
    set to the MP3 path, ``text`` left empty (stub chapter).

* After all chapters are inserted, sessions are rebuilt automatically.
"""

from __future__ import annotations

import json
import re
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .paths import PROJECTS_DIR
from .projects import _new_id, _now, load_project, rebuild_sessions, save_project


# ── Scan result ──────────────────────────────────────────────────────────────

@dataclass
class FolderScanItem:
    """One MP3 file found during a folder scan."""
    mp3_path: Path
    title: str
    source_text: str = ""
    voice: str = ""
    speed: float = 1.0
    has_sidecar: bool = False
    sidecar: dict[str, Any] = field(default_factory=dict)


@dataclass
class FolderImportSummary:
    """Result returned by :func:`import_mp3_folder`."""
    total: int = 0
    imported_with_sidecar: int = 0
    imported_as_stub: int = 0
    sessions_built: int = 0
    skipped: int = 0


# ── Helpers ───────────────────────────────────────────────────────────────────

def _natural_key(path: Path) -> list[int | str]:
    """Sort key for natural (human) sort order on filenames."""
    parts: list[int | str] = []
    for token in re.split(r"(\d+)", path.stem):
        parts.append(int(token) if token.isdigit() else token.lower())
    return parts


def _chapter_title_from_sidecar(sidecar: dict[str, Any], fallback: str) -> str:
    """Derive a chapter title from sidecar metadata."""
    title = str(sidecar.get("title", "")).strip()
    part = str(sidecar.get("part", "")).strip()
    if title and part:
        return f"{title} — {part}"
    if title:
        return title
    if part:
        return part
    return fallback


def _title_from_filename(stem: str) -> str:
    """Turn a filename stem into a readable title."""
    # Strip leading date-like prefixes before any other cleanup
    # Matches YYYY-MM-DD, YYYY_MM_DD, DD-MM-YYYY, DD_MM_YYYY (with sep = [-_ ])
    cleaned = re.sub(r"^\d{4}[-_ ]\d{2}[-_ ]\d{2}[-_ ]*", "", stem)
    cleaned = re.sub(r"^\d{2}[-_ ]\d{2}[-_ ]\d{4}[-_ ]*", "", cleaned)
    # Replace hyphens/underscores with spaces and title-case
    cleaned = re.sub(r"[-_]+", " ", cleaned).strip()
    return cleaned.title() if cleaned else stem


# ── Scanning ──────────────────────────────────────────────────────────────────

def scan_mp3_folder(folder: str | Path) -> list[FolderScanItem]:
    """Return one :class:`FolderScanItem` per MP3 found in *folder*.

    Files are returned in natural sort order by filename.  Subdirectories are
    not traversed.

    Args:
        folder: Path to a directory containing ``.mp3`` files.

    Returns:
        Sorted list of :class:`FolderScanItem` objects.  Empty if the folder
        contains no MP3 files.

    Raises:
        ValueError: if *folder* is not an existing directory.
    """
    folder = Path(folder).expanduser().resolve()
    if not folder.is_dir():
        raise ValueError(f"Not a directory: {folder}")

    items: list[FolderScanItem] = []
    for mp3_path in sorted(folder.glob("*.mp3"), key=_natural_key):
        fallback_title = _title_from_filename(mp3_path.stem)
        sidecar_path = mp3_path.with_suffix(".json")
        sidecar: dict[str, Any] = {}
        has_sidecar = False
        title = fallback_title
        source_text = ""
        voice = ""
        speed = 1.0

        if sidecar_path.exists():
            try:
                sidecar = json.loads(sidecar_path.read_text(encoding="utf-8"))
                has_sidecar = True
                title = _chapter_title_from_sidecar(sidecar, fallback_title)
                source_text = str(sidecar.get("source_text", "")).strip()
                voice = str(sidecar.get("voice", "")).strip()
                speed = float(sidecar.get("speed", 1.0) or 1.0)
            except (json.JSONDecodeError, OSError, ValueError):
                has_sidecar = False
                sidecar = {}

        items.append(
            FolderScanItem(
                mp3_path=mp3_path,
                title=title,
                source_text=source_text,
                voice=voice,
                speed=speed,
                has_sidecar=has_sidecar,
                sidecar=sidecar,
            )
        )

    return items


# ── Import ────────────────────────────────────────────────────────────────────

def import_mp3_folder(
    project_id: str,
    folder: str | Path,
    *,
    root: Path = PROJECTS_DIR,
) -> tuple[FolderImportSummary, dict[str, Any] | None]:
    """Scan *folder* for MP3s and append them as chapters to *project_id*.

    Chapters are appended in natural filename order.  Existing chapters are
    left untouched.  Sessions are rebuilt after import.

    Args:
        project_id: ID of the target project.
        folder:     Directory to scan.
        root:       Projects directory (override for testing).

    Returns:
        A ``(summary, project)`` tuple.  *project* is ``None`` if *project_id*
        does not exist.  *summary* contains counts of what was imported.

    Raises:
        ValueError: if *folder* is not an existing directory.
    """
    project = load_project(project_id, root)
    if project is None:
        return FolderImportSummary(), None

    items = scan_mp3_folder(folder)
    if not items:
        return FolderImportSummary(), project

    summary = FolderImportSummary()
    import_id = uuid.uuid4().hex[:10]
    imported_at = _now()

    for index, item in enumerate(items, start=1):
        output_path_str = str(item.mp3_path)
        status = "generated" if item.has_sidecar else "draft"

        chapter: dict[str, Any] = {
            "id": _new_id(),
            "title": item.title,
            "text": item.source_text,
            "status": status,
            "output_path": output_path_str,
            "import_source": {
                "import_id": import_id,
                "kind": "mp3_folder",
                "name": item.mp3_path.name,
                "path": output_path_str,
                "chapter_index": index,
                "chapter_count": len(items),
                "imported_at": imported_at,
            },
            "created_at": _now(),
            "updated_at": _now(),
        }
        project["chapters"].append(chapter)

        if item.has_sidecar:
            summary.imported_with_sidecar += 1
        else:
            summary.imported_as_stub += 1

    summary.total = len(items)

    # Rebuild sessions over the full (old + new) chapter list
    project["sessions"] = []
    project["updated_at"] = _now()
    saved = save_project(project, root=root)

    # rebuild_sessions loads from disk, so we call it after saving
    sessions = rebuild_sessions(project_id, root=root)
    summary.sessions_built = len(sessions)

    # Return the freshly saved project (sessions included)
    final = load_project(project_id, root)
    return summary, final
